language: java

cache:
  directories:
  - $HOME/google-cloud-sdk

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
- gcloud version || true
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  # The install script errors if this directory already exists,
  # but Travis already creates it when we mark it as cached.
  rm -rf $HOME/google-cloud-sdk;
  # The install script is overly verbose, which sometimes causes
  # problems on Travis, so ignore stdout.
  curl https://sdk.cloud.google.com | bash > /dev/null;
  fi

# Add gcloud to $PATH
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud version

before_script:
- gcloud beta emulators datastore start &
- gcloud beta emulators datastore env-init